Repository v7labs/darwin-py, pull requests merged in 2021-12, with the labels that each got.

#288 Documented Public API of cli_functions.py
  darwin/cli_functions.py
Labels: documentation, wind-team

#289 V7 2357 import classifications as tags
  darwin/importer/formats/labelbox.py
  darwin/importer/formats/labelbox_schemas.py
  tests/darwin/importer/formats/import_labelbox_test.py
Labels: enhancement, wind-team

#290 version bump v0.7.2
  darwin/__init__.py
Labels: documentation, enhancement, wind-team

#293 Added docs
  darwin/config.py
Labels: documentation, wind-team

#294 Added docs
  darwin/exceptions.py
Labels: documentation, wind-team

#287 V7 2428 harmonize api for clientpy
  darwin/cli_functions.py
  darwin/client.py
  darwin/dataset/download_manager.py
  darwin/dataset/remote_dataset.py
  darwin/dataset/upload_manager.py
  darwin/exceptions.py
  darwin/importer/importer.py
  tests/darwin/cli_functions_test.py
  tests/darwin/client_test.py
  tests/darwin/dataset/remote_dataset_test.py
  tests/darwin/dataset/upload_manager_test.py
Labels: documentation, enhancement, wind-team

#296 Fix docs GitHub flow
  .github/workflows/document.yml
Labels: bug, documentation, wind-team

#297 fixing code blocks
  darwin/importer/formats/labelbox.py
Labels: bug, documentation

#295 Adding docs datatypes.py P1
  darwin/config.py
  darwin/datatypes.py
  darwin/importer/formats/labelbox.py
  darwin/torch/dataset.py
Labels: documentation, wind-team

#300 Import Point Vector for SuperAnnotate
  darwin/dataset/utils.py
  darwin/importer/formats/__init__.py
  darwin/importer/formats/coco.py
  darwin/importer/formats/csvtags.py
  darwin/importer/formats/csvtagsvideo.py
  darwin/importer/formats/darwin.py
  darwin/importer/formats/dataloop.py
  darwin/importer/formats/labelbox.py
  darwin/importer/formats/pascalvoc.py
  darwin/importer/formats/superannotate.py
  darwin/importer/formats/superannotate_schemas.py
  tests/darwin/importer/formats/import_labelbox_test.py
  tests/darwin/importer/formats/import_pascalvoc_test.py
  tests/darwin/importer/formats/import_superannotate_test.py
Labels: enhancement, wind-team

#304 Added Ellipse Vector import for superannotate
  darwin/datatypes.py
  darwin/importer/formats/labelbox_schemas.py
  darwin/importer/formats/superannotate.py
  darwin/importer/formats/superannotate_schemas.py
  tests/darwin/importer/formats/import_superannotate_test.py
Labels: enhancement, wind-team

#308 Added import support for SuperAnnotate cuboid vectors
  darwin/datatypes.py
  darwin/importer/formats/superannotate.py
  darwin/importer/formats/superannotate_schemas.py
  tests/darwin/importer/formats/import_superannotate_test.py
Labels: enhancement, wind-team

#313 Adding import support for SuperAnnotate polygons
  darwin/datatypes.py
  darwin/importer/formats/superannotate.py
  darwin/importer/formats/superannotate_schemas.py
  tests/darwin/importer/formats/import_superannotate_test.py
Labels: documentation, enhancement, wind-team

#310 Adding support for superannotate bbox import
  darwin/importer/formats/superannotate.py
  darwin/importer/formats/superannotate_schemas.py
  tests/darwin/importer/formats/import_superannotate_test.py
Labels: enhancement, wind-team

#314 Addded polyline import support for SuperAnnotate
  darwin/datatypes.py
  darwin/importer/formats/superannotate.py
  darwin/importer/formats/superannotate_schemas.py
  tests/darwin/importer/formats/import_superannotate_test.py
Labels: documentation, enhancement, wind-team

#318 added more docs
  darwin/datatypes.py
Labels: documentation, wind-team

#316 [Refactor] Split Management
  darwin/dataset/split_manager.py
  tests/darwin/dataset/split_manager_test.py
Labels: bug, documentation, wind-team

#317 added superannotate types to class name
  darwin/importer/formats/superannotate.py
  tests/darwin/importer/formats/import_superannotate_test.py
Labels: enhancement, wind-team

#319 V7 2629 support attributes
  darwin/datatypes.py
  darwin/importer/formats/superannotate.py
  darwin/importer/formats/superannotate_schemas.py
  darwin/importer/importer.py
  tests/darwin/importer/formats/import_pascalvoc_test.py
  tests/darwin/importer/formats/import_superannotate_test.py
Labels: documentation, enhancement, wind-team

#320 Added support for superannotate tags
  darwin/importer/formats/superannotate.py
  darwin/importer/formats/superannotate_schemas.py
  tests/darwin/importer/formats/import_labelbox_test.py
  tests/darwin/importer/formats/import_superannotate_test.py
Labels: documentation, enhancement, wind-team

#321 Version bump with hotifx
  darwin/__init__.py
  darwin/importer/formats/superannotate.py
Labels: enhancement
