Repository v7labs/darwin-py, pull requests merged in 2022-02, with the labels that each got.

#336 Added docs to identifier.py
  darwin/dataset/identifier.py
Labels: documentation, wind-team

#339 Hotfix/compute distributions
  darwin/dataset/utils.py
  setup.py
Labels: bug, wind-team

#340 version bump
  darwin/version/__init__.py
Labels: wind-team

#335 Adding docs to download_manager.py
  darwin/dataset/download_manager.py
Labels: documentation, wind-team

#341 Added docs to darwin/dataset/remote_dataset.py
  darwin/client.py
  darwin/dataset/remote_dataset.py
Labels: documentation, wind-team

#345 [HOTFIX] Fixing a bug where response headers are not being correctly identified
  darwin/client.py
  tests/darwin/client_test.py
Labels: bug, wind-team

#344 Fixed inline code-blocks
  darwin/dataset/remote_dataset.py
  darwin/importer/formats/pascal_voc.py
Labels: documentation, wind-team

#348 Added docs to darwin/dataset/utils.py
  darwin/dataset/utils.py
Labels: documentation, wind-team

#349 Added docs to darwin/exporter/exporter.py
  darwin/exporter/exporter.py
Labels: documentation, wind-team

#337 V7 2239 darwin/dataset/local_dataset.py
  darwin/dataset/local_dataset.py
Labels: documentation, wind-team

#333 Adding docs to release.py
  darwin/client.py
  darwin/dataset/release.py
Labels: documentation, wind-team

#350 V7 2246 darwin/exporter/formats/coco.py
  darwin/exporter/formats/coco.py
  darwin/exporter/formats/dataloop.py
  darwin/exporter/formats/numpy_encoder.py
  tests/darwin/exporter/formats/export_coco_test.py
Labels: documentation, wind-team

#356 added docs to darwin/exporter/formats/dataloop.py
  darwin/exporter/formats/dataloop.py
Labels: documentation, wind-team

#358 Hotfix cyclical deps and zips
  darwin/client.py
  darwin/dataset/release.py
  darwin/version/__init__.py
Labels: bug, wind-team

#355 Added docs to dariwn/exporter/formats/darwin.py
  darwin/exporter/formats/darwin.py
Labels: documentation, wind-team

#359 fixing failure to fetch files with commas
  darwin/dataset/remote_dataset.py
  tests/darwin/dataset/remote_dataset_test.py
Labels: bug, wind-team

#360 Addes --yes flag to skip prompts when importing
  darwin/cli.py
  darwin/cli_functions.py
  darwin/importer/importer.py
  darwin/options.py
  tests/darwin/cli_functions_test.py
Labels: enhancement, wind-team
