Repository v7labs/darwin-py, pull requests merged in 2022-04, with the labels that each got.

#391 Added note to update docs
  darwin/exporter/formats/__init__.py
  darwin/importer/formats/__init__.py
Labels: documentation, wind-team

#380 Adding docs to torch/dataset.py
  darwin/torch/dataset.py
Labels: documentation

#384 Added docs for list files
  darwin/options.py
Labels: bug, documentation

#385 Listing files now prints a rich table.
  darwin/cli_functions.py
Labels: enhancement, wind-team

#382 improving docs for darwin exports
  darwin/cli_functions.py
  darwin/options.py
Labels: documentation

#373 Reduce API surface. Improved docs.
  darwin/importer/importer.py
Labels: documentation

#383 fixed dataset export not working with class ids
  darwin/cli_functions.py
  darwin/dataset/remote_dataset.py
  darwin/options.py
Labels: bug, documentation, wind-team

#388 fixed val-percentage and test-percentage being optional
  darwin/options.py
Labels: bug, documentation, wind-team

#394 Make class IDs list optional when generating a new dataset export
  darwin/cli.py
  darwin/cli_functions.py
  darwin/dataset/remote_dataset.py
  darwin/options.py
Labels: bug, wind-team

#393 Delete non existent files
  darwin/cli_functions.py
  darwin/client.py
  darwin/datatypes.py
  tests/darwin/cli_functions_test.py
Labels: bug, wind-team

#397 fixing typo
  darwin/options.py
Labels: bug, documentation

#399 [SWAT-48] fixing coco imports not working
  darwin/importer/formats/coco.py
Labels: bug, wind-team

#400 Completed docs
  darwin/torch/dataset.py
Labels: documentation, enhancement

#402 added docs, fixed types
  darwin/torch/transforms.py
Labels: bug, documentation, wind-team

#403 Added docs to utils.py
  darwin/torch/utils.py
Labels: documentation, wind-team

#401 Platform now allows same class name with different main type; revert checking
  darwin/importer/importer.py
Labels: enhancement, wind-team

#404 version bump to v0.7.14
  darwin/version/__init__.py
Labels: wind-team
