Repository v7labs/darwin-py, pull requests merged in 2022-03, with the labels that each got.

#365 added docs to darwin/exporter/formats/semantic_mask.py
  darwin/exporter/formats/semantic_mask.py
Labels: documentation, wind-team

#363 added docs to darwin/exporter/formats/instance_mask.py
  darwin/exporter/formats/instance_mask.py
Labels: documentation, wind-team

#366 supporting python 3.6 again
  .github/workflows/document.yml
  .github/workflows/tests.yml
  setup.py
Labels: bug, wind-team

#364 Added docs and trimmed API surface of darwin/exporter/formats/pascalv…
  darwin/exporter/formats/pascalvoc.py
Labels: documentation, wind-team

#368 Detect if new class will clash with existing class of different type.
  darwin/importer/importer.py
Labels: enhancement, wind-team

#377 Added docs
  darwin/importer/formats/darwin.py
Labels: documentation

#376 Added docs
  darwin/importer/formats/csv_tags_video.py
Labels: documentation

#375 Added docs
  darwin/importer/formats/csv_tags.py
Labels: documentation

#374 Reduced api surface. Added docs.
  darwin/importer/formats/coco.py
Labels: documentation

#390 fixed typo
  darwin/options.py
Labels: bug, documentation, wind-team

#386 Fixed incorrect description of help command
  darwin/options.py
Labels: bug, documentation, wind-team
